name: ci
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: Codegen And Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Run Tests
        run: go test -race -v -count=1 ./...

  lint-code:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --timeout 5m

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - tests
      - lint-code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
